apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app
  namespace: testing-kubernetes
spec:
  replicas: 3
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        run: app
    spec:
      containers:
      - name: nginx
        image: nginx:1.11
        ports:
        - name: nginx-http
          containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
          readOnly: true
      - name: hello-world
        image: pwwebdev/testing-kubernetes:${TRAVIS_BUILD_NUMBER}
        ports:
        - containerPort: 3000
      volumes:
      - configMap:
          name: nginx-config
        name: nginx-config
