apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: app
  name: app
  namespace: testing-kubernetes
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      run: app
  template:
    metadata:
      labels:
        run: app
    spec:
      containers:
      - image: nginx:1.11
        name: nginx
        ports:
        - name: nginx-http
          containerPort: 80
        volumeMounts:
        - mountPath: /etc/nginx/conf.d
          name: nginx-config
          readOnly: true
      - image: pwwebdev/testing-kubernetes:${BUILD_NUMBER}
        name: hello-world
        ports:
        - containerPort: 3000
      volumes:
      - configMap:
          name: nginx-config
        name: nginx-config
