apiVersion: v1
kind: Service
metadata:
  labels:
    run: app
  name: app
  namespace: testing-kubernetes
spec:
  ports:
  - port: 80
    targetPort: nginx-http
  selector:
    run: app
  sessionAffinity: None
  type: LoadBalancer
