sudo: required

services:
  - docker

env:
  PROJECT_NAME: testing-145512
  CLUSTER_NAME: cluster-1
  CLOUDSDK_COMPUTE_ZONE: europe-west1-d
  CLOUDSDK_CORE_DISABLE_PROMPTS: 1

before_install:
  - export REPO=pwwebdev/testing-kubernetes
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -t $REPO:$TRAVIS_COMMIT src/
  - docker login --email=$DOCKER_HUB_EMAIL --username=$DOCKER_HUB_USERNAME --password=$DOCKER_HUB_PASSWORD
  - docker tag $REPO:$TRAVIS_COMMIT $REPO:$TAG
  - docker tag $REPO:$TRAVIS_COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO
  - gcloud version
  - sudo gcloud -q components install kubectl || true
  - echo $GCLOUD_SERVICE_KEY | base64 --decode -i > ${HOME}/gcloud-service-key.json
  - gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json
  - gcloud config set project $PROJECT_NAME
  - gcloud --quiet config set container/cluster $CLUSTER_NAME
  - gcloud config set compute/zone ${CLOUDSDK_COMPUTE_ZONE}
  - gcloud --quiet container clusters get-credentials $CLUSTER_NAME

script:
  - ./deploy.sh travis-$TRAVIS_BUILD_NUMBER
