sudo: required

services:
  - docker

before_install:
  - docker build -t pwwebdev/testing-kubernetes src/
  - docker login --email=$DOCKER_HUB_EMAIL --username=$DOCKER_HUB_USERNAME --password=$DOCKER_HUB_PASSWORD
  - docker push pwwebdev/testing-kubernetes
