sudo: required

services:
- docker

env:
- PROJECT_NAME=testing-145512 CLUSTER_NAME=cluster-1 CLOUDSDK_COMPUTE_ZONE=europe-west1-d CLOUDSDK_CORE_DISABLE_PROMPTS=1

before_install:
- openssl aes-256-cbc -K $encrypted_29882342a6cb_key -iv $encrypted_29882342a6cb_iv -in conf/gke/credentials.json.enc -out credentials.json -d
- export REPO=pwwebdev/testing-kubernetes
- export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
- export TAG=`if [ "$BRANCH" == "master" ]; then echo "latest"; else echo $BRANCH; fi`
- docker build -t $REPO:$TRAVIS_COMMIT src/
- docker login --email=$DOCKER_HUB_EMAIL --username=$DOCKER_HUB_USERNAME --password=$DOCKER_HUB_PASSWORD
- docker tag $REPO:$TRAVIS_COMMIT $REPO:$TAG
- docker tag $REPO:$TRAVIS_COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
- docker push $REPO
- gcloud version
- sudo gcloud -q components install kubectl || true
- cat credentials.json
- sudo gcloud auth activate-service-account --key-file credentials.json
- sudo gcloud config set project $PROJECT_NAME
- sudo gcloud --quiet config set container/cluster $CLUSTER_NAME
- sudo gcloud config set compute/zone ${CLOUDSDK_COMPUTE_ZONE}
- sudo gcloud --quiet container clusters get-credentials $CLUSTER_NAME
- sudo gcloud --version

script:
- which kubectl
- "./deploy.sh travis-$TRAVIS_BUILD_NUMBER"
