sudo: required

services:
  - docker

env:
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1

before_install:
  - export REPO=pwwebdev/testing-kubernetes
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -t $REPO:$TRAVIS_COMMIT src/
  - docker login --email=$DOCKER_HUB_EMAIL --username=$DOCKER_HUB_USERNAME --password=$DOCKER_HUB_PASSWORD
  - docker tag $REPO:$TRAVIS_COMMIT $REPO:$TAG
  - docker tag $REPO:$TRAVIS_COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO
  - gcloud version
  - gcloud components update kubectl || true

script:
  - ./deploy.sh $TRAVIS_BUILD_NUMBER
