sudo: required
cache:
  directories:
  - "$HOME/google-cloud-sdk/"
services:
- docker
env:
  CLOUDSDK_CORE_DISABLE_PROMPTS: 1
  KUBECONFIG: "/home/travis/build/kilian-siebel-consulting/testing-kubernetes/kubeconfig.json"
  REPO: pwwebdev/testing-kubernetes
before_install:
- openssl aes-256-cbc -K $encrypted_b50d7e500e5c_key -iv $encrypted_b50d7e500e5c_iv
  -in conf/azure/kubeconfig.json.enc -out kubeconfig.json -d
- docker login --username=$DOCKER_HUB_USERNAME --password=$DOCKER_HUB_PASSWORD
install:
- docker build -t $REPO:$TRAVIS_BUILD_NUMBER src/
- docker tag $REPO:$TRAVIS_BUILD_NUMBER $REPO:latest
- docker push $REPO:$TRAVIS_BUILD_NUMBER
- docker push $REPO:latest
- if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; curl
  https://sdk.cloud.google.com | bash; fi
- source /home/travis/google-cloud-sdk/path.bash.inc
- gcloud --quiet components install kubectl
script:
- "./deploy.sh"
notifications:
  email: false
  slack:
    on_success: change
    on_failure: change
    rooms:
      secure: i7LkrbzojhjPxVjUetTpeS5tDG45CZ/p7jRFbwOzm7YKpOuJhJYNNVudD2NBAzG3HgQIXbIzWdVHVoqhW9/a5nnbtK7wIOoIgycBY5noL1iSDCHcUVzYhbxK3I0YzS2ZP6SWq+u1I562wT3PYOGnakhZuMs0lauAK2ls2hBCho6+XoBzl5Gbwp9drM7pKwBGXgbdq/owsHvSMxdCRxe23ikFbJmXMOnhsLnruqxkfHoIsvNoKCXzuXqhSI7q3QBTkFHdSAmLcDCUDsPQKeRoqBLf5UVFD9e3GRU7+2HXsxWrFaAFo7X6AWo2oTCgAiCk78RTCg9DQtqiUKpRn7v5wZcKZ2c7ZlY+mEXPUItDm6RWaVAwixG5rG72yWd9RwarXnxi3ji8iFM0++FyDN6Ag/lvE7q98NfvYxIeNPIT+qIs8U70hSwjxzF4J3eTRp0qgmG8UvQ5G4JZAPstXpNKf00vD6bjxhoNrTubbspor54w9Ij64neSnZw7ycjZtqfl4x4K3HVsBzR1vx7dEEqFPnqB8/ecuVMqk77HpWMTEefY9GVw9MOS+RJbLVS6N5H89pJC6BZfGhQn9Gwlw4loyQNTUOBEtzEae0+F6M09y8flm4VHFhRQbIykQXct7a+RPWdmhCHtJX2k+/jO+ixKXntjkJiUQEv7uyid4KMm9PY=
