sudo: required
cache:
  directories:
    - "$HOME/google-cloud-sdk/"

services:
- docker

env:
  GC_PROJECT_NAME: testing-145512
  GC_CLUSTER_NAME: cluster-1
  GC_COMPUTE_ZONE: europe-west1-d
  CLOUDSDK_CORE_DISABLE_PROMPTS: 1
  GOOGLE_APPLICATION_CREDENTIALS: /home/travis/build/kilian-siebel-consulting/testing-kubernetes/credentials.json
  REPO: pwwebdev/testing-kubernetes

before_install:
- openssl aes-256-cbc -K $encrypted_29882342a6cb_key -iv $encrypted_29882342a6cb_iv -in conf/gke/credentials.json.enc -out credentials.json -d
- docker build -t $REPO:$TRAVIS_BUILD_NUMBER src/
- docker login --username=$DOCKER_HUB_USERNAME --password=$DOCKER_HUB_PASSWORD
- docker push $REPO:$TRAVIS_BUILD_NUMBER
- if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; curl https://sdk.cloud.google.com | bash; fi
- source /home/travis/google-cloud-sdk/path.bash.inc
- gcloud --quiet components install kubectl
#- gcloud auth activate-service-account --key-file credentials.json
#- gcloud config set project ${GC_PROJECT_NAME}
#- gcloud --quiet config set container/cluster ${GC_CLUSTER_NAME}
#- gcloud config set compute/zone ${GC_COMPUTE_ZONE}
#- gcloud --quiet container clusters get-credentials ${GC_CLUSTER_NAME}

script:
- "./deploy.sh travis-$TRAVIS_BUILD_NUMBER"
