sudo: required

services:
  - docker

before_install:
  - docker build -t pwwebdev/testing-kubernetes src/
  - docker login --username=$DOCKER_HUB_USERNAME --password=$
  - docker push pwwebdev/testing-kubernetes

script:
  - ./deploy.sh $TRAVIS_BUILD_NUMBER
