sudo: required
cache:
  directories:
    - "$HOME/google-cloud-sdk/"

services:
- docker

env:
  PROJECT_NAME=testing-145512
  CLUSTER_NAME=cluster-1
  CLOUDSDK_COMPUTE_ZONE=europe-west1-d
  CLOUDSDK_CORE_DISABLE_PROMPTS=1
  GOOGLE_APPLICATION_CREDENTIALS=/home/travis/build/kilian-siebel-consulting/testing-kubernetes/credentials.json

before_install:
- pwd
- openssl aes-256-cbc -K $encrypted_29882342a6cb_key -iv $encrypted_29882342a6cb_iv -in conf/gke/credentials.json.enc -out credentials.json -d
- export REPO=pwwebdev/testing-kubernetes
- export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
- export TAG=`if [ "$BRANCH" == "master" ]; then echo "latest"; else echo $BRANCH; fi`
- docker build -t $REPO:$TRAVIS_COMMIT src/
- docker login --email=$DOCKER_HUB_EMAIL --username=$DOCKER_HUB_USERNAME --password=$DOCKER_HUB_PASSWORD
- docker tag $REPO:$TRAVIS_COMMIT $REPO:$TAG
- docker tag $REPO:$TRAVIS_COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
- docker push $REPO
- gcloud version || true
- if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
# Add gcloud to $PATH
- source /home/travis/google-cloud-sdk/path.bash.inc
- gcloud version
- which gcloud
- gcloud -q components install kubectl
- cat credentials.json
- gcloud auth activate-service-account --key-file credentials.json
- gcloud config set project $PROJECT_NAME
- gcloud --quiet config set container/cluster $CLUSTER_NAME
- gcloud config set compute/zone ${CLOUDSDK_COMPUTE_ZONE}
- gcloud --quiet container clusters get-credentials $CLUSTER_NAME
- gcloud --version

script:
- "./deploy.sh travis-$TRAVIS_BUILD_NUMBER"
